---
all:
  hosts:
    netbox:
      ansible_host: "{{ lookup('env', 'INTERNAL_NIC_IP') | regex_replace('/.*', '') }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ../.ssh/id_ed25519
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -L 3128:localhost:3128'
